# Defines the version of the configuration format
version: 0.1

# Services are a collection of workloads that work together
services:
  # Defines a workload named 'jupiter'
  OllamaNode:
    # Specify the container image name; Make sure image is public
    image: notboredgoon/ollama_node:v1

    # Determines when to fetch the latest version of the workload
    imagePullPolicy: Always

    # Defines the command to run; empty by default
    command: []

    # Specifies arguments for the command; empty by default
    args: []

    # Defines network-related settings
    ports:
      - containerPort: 11434 # The port on which the service will be available
        protocol: TCP # The protocol used for communication
        expose: true # This will generate the URL for the service, so it can be accessed from the internet

    # Defines environment variables for the workload
    env:
      - name: models # Environment variable name
        value: "{{.Ollama}}" # Placeholder for dynamic value substitution; It means whenever someone try to deploy this service, they need to provide a value for this variable.
        default: llama3:8b, mistral:7b, codegemma # Default value for the environment variable

    # Specifies the minimum resource allocation
    # This also specify the template price
    resourceUsage:
      idle:
        cpu: 400 # CPU allocation (likely in millicores, meaning 0.2 cores)
        memory: 400 # Memory allocation (likely in MB)


  ######## Constraints ########
  # 1. Maximum 5 services can be deployed.
  # 2. CU = max(total CPU, total Memory); Max 4 CUs can be deployed.
  # 3. One service can be expose outside the world.
  # 4. In upgrade template does not allow to add service(s) / update service(s) resources.
  ######## Constraints ########
